### ISSUE TITLE
Couldn't fine u2fval-client from pip install

### ISSUE THREAD

**Issue by kynwu** [Yubico/u2fval-client-python#1]
Could not find a version that satisfies the requirement u2fval-client (from versions: )
No matching distribution found for u2fval-client

please suppoort

**Comment by dainnilsson** [comment]
Sorry, there hasn't been a release of this made yet, so the README is incorrect in giving those instructions. Until we've published an actual release, you can install by checking out the repository and running "pip install ." from within the root of the repository.

**Comment by dainnilsson** [comment]
Whoops, didn't mean to re-close this just now.
